import Image from 'next/image'
import { css } from '@emotion/react'

// Utils
import { useIsMobile } from '#utils/hooks'

// Styles
import { Color, mqMobile } from '#styles/index'

// Assets
import desktopStep1Svg from '#assets/how-it-works-desktop-step-1.svg'
import desktopStep2Svg from '#assets/how-it-works-desktop-step-2.svg'
import desktopStep3Svg from '#assets/how-it-works-desktop-step-3.svg'
import mobileStep1Svg from '#assets/how-it-works-mobile-step-1.svg'
import mobileStep2Svg from '#assets/how-it-works-mobile-step-2.svg'

export const Cards = () => {
	const isMobile = useIsMobile()

	const cards = [
		{
			stepNumber: 1,
			imageSrc: isMobile ? mobileStep1Svg : desktopStep1Svg,
			text: 'Select an asset you want to lend or provide as liquidity',
		},
		{
			stepNumber: 2,
			imageSrc: isMobile ? mobileStep2Svg : desktopStep2Svg,
			text: isMobile
				? 'Choose a strategy available for your asset based on your risk preferences'
				: "Pool's funds collateralise option perpetual strategy",
		},
		{
			stepNumber: 3,
			imageSrc: isMobile ? null : desktopStep3Svg,
			text: isMobile ? (
				<div>
					Your autogenerated liquidity tokens are secured by insurance, invested and earn{' '}
					<span style={{ color: Color.Blue1 }}>best</span> yield in DeFi
				</div>
			) : (
				'Sold options generate weekly yield'
			),
		},
	]

	return (
		<div
			css={css`
				display: flex;
				justify-content: space-around;
				padding-bottom: 100px;
				background: linear-gradient(180deg, #333398 0%, #383dc1 96.35%);
				${mqMobile} {
					flex-direction: column;
					row-gap: 15px;
					padding: 0 15px 50px;
				}
			`}
		>
			{cards.map(({ imageSrc, stepNumber, text }) => (
				<div
					css={css`
						display: grid;
						grid-template-rows: 65px 22px 44px;
						row-gap: 13px;
						height: 234px;
						width: 338px;
						padding: 33px 0 0;
						background-color: ${Color.Violet7};
						border: 1px solid ${Color.Violet8};
						border-radius: 8px;
						${mqMobile} {
							grid-template-rows: auto auto auto;
							height: auto;
							width: auto;
							padding: 20px 30px;
						}
					`}
					key={stepNumber}
				>
					{imageSrc && <Image alt="" src={imageSrc} />}

					<div
						css={css`
							color: ${Color.Violet6};
							font-size: 18px;
							font-weight: 600;
							line-height: 22px;
							text-align: center;
							${mqMobile} {
								color: ${Color.Violet22};
							}
						`}
					>
						Step {stepNumber}
					</div>
					<div
						css={css`
							padding: 5px 19px 0;
							color: white;
							font-size: 18px;
							font-weight: 600;
							line-height: 22px;
							text-align: center;
							${mqMobile} {
								padding: 5px 0 0;
								font-size: 14px;
								font-weight: 600;
								line-height: 17px;
							}
						`}
					>
						{text}
					</div>
				</div>
			))}
		</div>
	)
}
